# Generated by Django 3.1 on 2022-03-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('tour_images', models.ImageField(blank=True, upload_to='photos/tours')),
                ('num_person', models.IntegerField(blank=True)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('epidemic_level', models.IntegerField(blank=True)),
                ('place_recommended', models.CharField(max_length=200)),
                ('classify', models.CharField(max_length=100)),
            ],
        ),
    ]
